#!/bin/bash

# train and val
python src/main.py rnn/tbird default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.5 default.dir_name="paracheck010905" dataset.reverse=False network.encoder.name=gru_uni

python src/main.py bert/bgl default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.5 default.dir_name="paracheck010905" dataset.reverse=False 
python src/main.py rnn/bgl default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.5 default.dir_name="paracheck010905" dataset.reverse=False network.encoder.name=lstm_bi
python src/main.py rnn/bgl default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.5 default.dir_name="paracheck010905" dataset.reverse=False network.encoder.name=lstm_uni
python src/main.py rnn/bgl default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.5 default.dir_name="paracheck010905" dataset.reverse=False network.encoder.name=gru_bi
python src/main.py rnn/bgl default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.5 default.dir_name="paracheck010905" dataset.reverse=False network.encoder.name=gru_uni
python src/main.py mlp/bgl default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.5 default.dir_name="paracheck010905" dataset.reverse=False

python src/main.py bert/amiya default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.5 default.dir_name="paracheck010905" dataset.reverse=False 
python src/main.py rnn/amiya default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.5 default.dir_name="paracheck010905" dataset.reverse=False network.encoder.name=lstm_bi
python src/main.py rnn/amiya default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.5 default.dir_name="paracheck010905" dataset.reverse=False network.encoder.name=lstm_uni
python src/main.py rnn/amiya default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.5 default.dir_name="paracheck010905" dataset.reverse=False network.encoder.name=gru_bi
python src/main.py rnn/amiya default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.5 default.dir_name="paracheck010905" dataset.reverse=False network.encoder.name=gru_uni
python src/main.py mlp/amiya default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.5 default.dir_name="paracheck010905" dataset.reverse=False

python src/main.py bert/amiya2 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.5 default.dir_name="paracheck010905" dataset.reverse=False 
python src/main.py rnn/amiya2 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.5 default.dir_name="paracheck010905" dataset.reverse=False network.encoder.name=lstm_bi
python src/main.py rnn/amiya2 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.5 default.dir_name="paracheck010905" dataset.reverse=False network.encoder.name=lstm_uni
python src/main.py rnn/amiya2 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.5 default.dir_name="paracheck010905" dataset.reverse=False network.encoder.name=gru_bi
python src/main.py rnn/amiya2 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.5 default.dir_name="paracheck010905" dataset.reverse=False network.encoder.name=gru_uni
python src/main.py mlp/amiya2 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.5 default.dir_name="paracheck010905" dataset.reverse=False

python src/main.py bert/amiya default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0 loss.mask.bias=1 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck01065" dataset.reverse=False 
python src/main.py rnn/amiya default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0 loss.mask.bias=1 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck01065" dataset.reverse=False network.encoder.name=lstm_bi
python src/main.py rnn/amiya default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0 loss.mask.bias=1 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck01065" dataset.reverse=False network.encoder.name=lstm_uni
python src/main.py rnn/amiya default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0 loss.mask.bias=1 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck01065" dataset.reverse=False network.encoder.name=gru_bi
python src/main.py rnn/amiya default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0 loss.mask.bias=1 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck01065" dataset.reverse=False network.encoder.name=gru_uni
python src/main.py mlp/amiya default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0 loss.mask.bias=1 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck01065" dataset.reverse=False

python src/main.py bert/amiya2 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0 loss.mask.bias=1 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck01065" dataset.reverse=False 
python src/main.py rnn/amiya2 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0 loss.mask.bias=1 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck01065" dataset.reverse=False network.encoder.name=lstm_bi
python src/main.py rnn/amiya2 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0 loss.mask.bias=1 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck01065" dataset.reverse=False network.encoder.name=lstm_uni
python src/main.py rnn/amiya2 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0 loss.mask.bias=1 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck01065" dataset.reverse=False network.encoder.name=gru_bi
python src/main.py rnn/amiya2 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0 loss.mask.bias=1 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck01065" dataset.reverse=False network.encoder.name=gru_uni
python src/main.py mlp/amiya2 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0 loss.mask.bias=1 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck01065" dataset.reverse=False

python src/main.py bert/amiya default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0.5 loss.mask.bias=0.5 dataset.sample.mask_ratio=0.35 default.dir_name="paracheck0505035" dataset.reverse=False 
python src/main.py rnn/amiya default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0.5 loss.mask.bias=0.5 dataset.sample.mask_ratio=0.35 default.dir_name="paracheck0505035" dataset.reverse=False network.encoder.name=lstm_bi
python src/main.py rnn/amiya default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0.5 loss.mask.bias=0.5 dataset.sample.mask_ratio=0.35 default.dir_name="paracheck0505035" dataset.reverse=False network.encoder.name=lstm_uni
python src/main.py rnn/amiya default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0.5 loss.mask.bias=0.5 dataset.sample.mask_ratio=0.35 default.dir_name="paracheck0505035" dataset.reverse=False network.encoder.name=gru_bi
python src/main.py rnn/amiya default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0.5 loss.mask.bias=0.5 dataset.sample.mask_ratio=0.35 default.dir_name="paracheck0505035" dataset.reverse=False network.encoder.name=gru_uni
python src/main.py mlp/amiya default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0.5 loss.mask.bias=0.5 dataset.sample.mask_ratio=0.35 default.dir_name="paracheck0505035" dataset.reverse=False

python src/main.py bert/amiya2 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0.5 loss.mask.bias=0.5 dataset.sample.mask_ratio=0.35 default.dir_name="paracheck0505035" dataset.reverse=False 
python src/main.py rnn/amiya2 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0.5 loss.mask.bias=0.5 dataset.sample.mask_ratio=0.35 default.dir_name="paracheck0505035" dataset.reverse=False network.encoder.name=lstm_bi
python src/main.py rnn/amiya2 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0.5 loss.mask.bias=0.5 dataset.sample.mask_ratio=0.35 default.dir_name="paracheck0505035" dataset.reverse=False network.encoder.name=lstm_uni
python src/main.py rnn/amiya2 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0.5 loss.mask.bias=0.5 dataset.sample.mask_ratio=0.35 default.dir_name="paracheck0505035" dataset.reverse=False network.encoder.name=gru_bi
python src/main.py rnn/amiya2 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0.5 loss.mask.bias=0.5 dataset.sample.mask_ratio=0.35 default.dir_name="paracheck0505035" dataset.reverse=False network.encoder.name=gru_uni
python src/main.py mlp/amiya2 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0.5 loss.mask.bias=0.5 dataset.sample.mask_ratio=0.35 default.dir_name="paracheck0505035" dataset.reverse=False

python src/main.py bert/amiya default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0.5 loss.mask.bias=0.5 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0505065" dataset.reverse=False 
python src/main.py rnn/amiya default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0.5 loss.mask.bias=0.5 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0505065" dataset.reverse=False network.encoder.name=lstm_bi
python src/main.py rnn/amiya default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0.5 loss.mask.bias=0.5 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0505065" dataset.reverse=False network.encoder.name=lstm_uni
python src/main.py rnn/amiya default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0.5 loss.mask.bias=0.5 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0505065" dataset.reverse=False network.encoder.name=gru_bi
python src/main.py rnn/amiya default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0.5 loss.mask.bias=0.5 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0505065" dataset.reverse=False network.encoder.name=gru_uni
python src/main.py mlp/amiya default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0.5 loss.mask.bias=0.5 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0505065" dataset.reverse=False

python src/main.py bert/amiya2 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0.5 loss.mask.bias=0.5 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0505065" dataset.reverse=False 
python src/main.py rnn/amiya2 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0.5 loss.mask.bias=0.5 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0505065" dataset.reverse=False network.encoder.name=lstm_bi
python src/main.py rnn/amiya2 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0.5 loss.mask.bias=0.5 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0505065" dataset.reverse=False network.encoder.name=lstm_uni
python src/main.py rnn/amiya2 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0.5 loss.mask.bias=0.5 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0505065" dataset.reverse=False network.encoder.name=gru_bi
python src/main.py rnn/amiya2 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0.5 loss.mask.bias=0.5 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0505065" dataset.reverse=False network.encoder.name=gru_uni
python src/main.py mlp/amiya2 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0.5 loss.mask.bias=0.5 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0505065" dataset.reverse=False
