#!/bin/bash

python src/recovery_setup_config.py bert/amiya default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0 loss.mask.bias=1 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck01065" dataset.reverse=False 
python src/recovery_setup_config.py rnn/amiya default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0 loss.mask.bias=1 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck01065" dataset.reverse=False network.encoder.name=lstm_bi
python src/recovery_setup_config.py rnn/amiya default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0 loss.mask.bias=1 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck01065" dataset.reverse=False network.encoder.name=lstm_uni
python src/recovery_setup_config.py rnn/amiya default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0 loss.mask.bias=1 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck01065" dataset.reverse=False network.encoder.name=gru_bi
python src/recovery_setup_config.py rnn/amiya default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0 loss.mask.bias=1 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck01065" dataset.reverse=False network.encoder.name=gru_uni
python src/recovery_setup_config.py mlp/amiya default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0 loss.mask.bias=1 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck01065" dataset.reverse=False

python src/recovery_setup_config.py bert/amiya2 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0 loss.mask.bias=1 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck01065" dataset.reverse=False 
python src/recovery_setup_config.py rnn/amiya2 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0 loss.mask.bias=1 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck01065" dataset.reverse=False network.encoder.name=lstm_bi
python src/recovery_setup_config.py rnn/amiya2 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0 loss.mask.bias=1 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck01065" dataset.reverse=False network.encoder.name=lstm_uni
python src/recovery_setup_config.py rnn/amiya2 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0 loss.mask.bias=1 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck01065" dataset.reverse=False network.encoder.name=gru_bi
python src/recovery_setup_config.py rnn/amiya2 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0 loss.mask.bias=1 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck01065" dataset.reverse=False network.encoder.name=gru_uni
python src/recovery_setup_config.py mlp/amiya2 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:1" loss.hypersphere.bias=0 loss.mask.bias=1 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck01065" dataset.reverse=False