default:
  dir_name: outputs
  resource: "local"
  num_workers: 16
  epochs: 200
  r_seed: 31
  device_id: "cuda:3"
  deterministic: True
  check_val_every_n_epoch: 1
  early_stop_patience: 20
  monitor:
    name: "ValTotal"
    mode: "min"

network: 
  ver: "logbert"
  encoder:
      name: bert
      hidden_size: 256
      layer_num: 4
      attn_heads: 4
      dropout: 0.1
  is_logkey: True
  is_time: False
loss:
  num: 2
  mask:
    bias: 1.0
  hypersphere:
    bias: 0.0
dataset:
  name: "T1105"
  version: 1
  parser: True
  train_ratio: 0.8
  another_method: True
  dataset_dir: "../data/processed/Integrated"
  sample:
    window_size: 128
    adaptive_window: True
    seq_len: 256
    min_len: 10 
    mask_ratio: 0.65
    sample_ratio: 1
    valid_size: 0.1
  vocab:
    name: wordvocab
    vocab_size: 60
    min_freq: 1
eval:
  hypersphere_loss_test: False
  num_candidates: 15
  
optimizer:
  name: Adam
  scheduler:
    name: cosine 
  hp:
    lr: 0.00001
    weight_decay: 0.0005
    lr_decay: 0.0001
    lr_warmup_step: 10
    lr_warmup_init: 1e-6
    warmup_prefix: False
    batch_size: 32


