#!/bin/bash

# train and val
# python src/main.py bert/art3 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False 
# python src/main.py bert/art4 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False 
# python src/main.py bert/web1_3 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False 
# python src/main.py bert/web2_3 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False 
# python src/main.py bert/web3_3 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False 
# python src/main.py bert/web1_4 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False 
# python src/main.py bert/web2_4 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False 
# python src/main.py bert/web3_4 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False 

python src/main.py mlp/art3 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False 
python src/main.py mlp/art4 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False 
python src/main.py mlp/web1_3 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False 
python src/main.py mlp/web2_3 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False 
# python src/main.py mlp/web3_3 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False 
# python src/main.py mlp/web1_4 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False 
# python src/main.py mlp/web2_4 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False 
# python src/main.py mlp/web3_4 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False 

# python src/main.py rnn/art3 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False network.encoder.name=gru_uni
# python src/main.py rnn/art4 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False network.encoder.name=gru_uni
# python src/main.py rnn/web1_3 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False network.encoder.name=gru_uni
# python src/main.py rnn/web2_3 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False network.encoder.name=gru_uni
# python src/main.py rnn/web3_3 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False network.encoder.name=gru_uni
# python src/main.py rnn/web1_4 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False network.encoder.name=gru_uni
# python src/main.py rnn/web2_4 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False network.encoder.name=gru_uni
# python src/main.py rnn/web3_4 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False network.encoder.name=gru_uni

# python src/main.py rnn/art3 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False network.encoder.name=lstm_uni
# python src/main.py rnn/art4 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False network.encoder.name=lstm_uni
# python src/main.py rnn/web1_3 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False network.encoder.name=lstm_uni
# python src/main.py rnn/web2_3 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False network.encoder.name=lstm_uni
# python src/main.py rnn/web3_3 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False network.encoder.name=lstm_uni
# python src/main.py rnn/web1_4 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False network.encoder.name=lstm_uni
# python src/main.py rnn/web2_4 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False network.encoder.name=lstm_uni
# python src/main.py rnn/web3_4 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False network.encoder.name=lstm_uni

# python src/main.py rnn/art3 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False network.encoder.name=lstm_bi
# python src/main.py rnn/art4 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False network.encoder.name=lstm_bi
# python src/main.py rnn/web1_3 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False network.encoder.name=lstm_bi
# python src/main.py rnn/web2_3 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False network.encoder.name=lstm_bi
# python src/main.py rnn/web3_3 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False network.encoder.name=lstm_bi
# python src/main.py rnn/web1_4 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False network.encoder.name=lstm_bi
# python src/main.py rnn/web2_4 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False network.encoder.name=lstm_bi
# python src/main.py rnn/web3_4 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False network.encoder.name=lstm_bi

# python src/main.py rnn/art3 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False network.encoder.name=gru_bi
# python src/main.py rnn/art4 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False network.encoder.name=gru_bi
# python src/main.py rnn/web1_3 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False network.encoder.name=gru_bi
# python src/main.py rnn/web2_3 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False network.encoder.name=gru_bi
# python src/main.py rnn/web3_3 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False network.encoder.name=gru_bi
# python src/main.py rnn/web1_4 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False network.encoder.name=gru_bi
# python src/main.py rnn/web2_4 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False network.encoder.name=gru_bi
# python src/main.py rnn/web3_4 default.num_workers=16 dataset.train_ratio=6 dataset.sample.seq_len=128 default.device_id="cuda:2" loss.hypersphere.bias=0.1 loss.mask.bias=0.9 dataset.sample.mask_ratio=0.65 default.dir_name="paracheck0109065" dataset.reverse=False network.encoder.name=gru_bi
